from sqlalchemy import MetaData, Integer, String
from sqlalchemy.orm import DeclarativeBase, mapped_column

raw_metadata = MetaData(schema = "raw")

class Base(DeclarativeBase):
    metadata = raw_metadata

class Administrative(Base):
    __tablename__ = "administrative_segment"
    
    db_id = mapped_column(String, primary_key = True)
    segment_level = mapped_column(String(2))
    state_code = mapped_column(String(2))
    ori = mapped_column(String(9))
    incident_number = mapped_column(String(12))
    incident_date = mapped_column(Integer)
    report_date_indicator = mapped_column(String(1))
    incident_date_hour = mapped_column(Integer)
    total_offense_segments = mapped_column(Integer)
    total_victim_segments = mapped_column(Integer)
    total_offender_segments = mapped_column(Integer)
    total_arrestee_segments = mapped_column(Integer)
    city_submission = mapped_column(String(4))
    cleared_exceptionally = mapped_column(String(1))
    exceptional_clearance_date = mapped_column(Integer)
    
class Offense(Base):
    __tablename__ = "offense_segment"
    
    db_id = mapped_column(String, primary_key = True)
    segment_level = mapped_column(String(2))
    state_code = mapped_column(String(2))
    ori = mapped_column(String(9))
    incident_number = mapped_column(String(12))
    incident_date = mapped_column(Integer)
    ucr_offense_code = mapped_column(String(3))
    offense_attempted_or_completed = mapped_column(String(1))
    offender_suspected_of_using1 = mapped_column(String(1))
    offender_suspected_of_using2 = mapped_column(String(1))
    offender_suspected_of_using3 = mapped_column(String(1))
    location_type = mapped_column(String(2))
    num_premises_entered = mapped_column(String(2))
    method_of_entry = mapped_column(String(1))
    type_of_criminal_activity1 = mapped_column(String(1))
    type_of_criminal_activity2 = mapped_column(String(1))
    type_of_criminal_activity3 = mapped_column(String(1))
    type_weapon_force_involved1 = mapped_column(String(2))
    automatic_weapon_indicator1 = mapped_column(String(1))
    type_weapon_force_involved2 = mapped_column(String(2))
    automatic_weapon_indicator2 = mapped_column(String(1))
    type_weapon_force_involved3 = mapped_column(String(2))
    automatic_weapon_indicator3 = mapped_column(String(1))
    bias_motivation = mapped_column(String(2))
    
class Victim(Base):
    __tablename__ = "victim_segment"
    
    db_id = mapped_column(String, primary_key = True)
    segment_level = mapped_column(String(2))
    state_code = mapped_column(String(2))
    ori = mapped_column(String(9))
    incident_number = mapped_column(String(12))
    incident_date = mapped_column(Integer)
    victim_sequence_number = mapped_column(String(3))
    ucr_offense_code1 = mapped_column(String(3))
    ucr_offense_code2 = mapped_column(String(3))
    ucr_offense_code3 = mapped_column(String(3))
    ucr_offense_code4 = mapped_column(String(3))
    ucr_offense_code5 = mapped_column(String(3))
    ucr_offense_code6 = mapped_column(String(3))
    ucr_offense_code7 = mapped_column(String(3))
    ucr_offense_code8 = mapped_column(String(3))
    ucr_offense_code9 = mapped_column(String(3))
    ucr_offense_code10 = mapped_column(String(3))
    type_of_victim = mapped_column(String(1))
    age_of_victim = mapped_column(String(2))
    sex_of_victim = mapped_column(String(1))
    race_of_victim = mapped_column(String(1))
    ethnicity_of_victim = mapped_column(String(1))
    residence_status_of_victim = mapped_column(String(1))
    agg_assault_homicide_circumstance1 = mapped_column(String(2))
    agg_assault_homicide_circumstance2 = mapped_column(String(2))
    additional_justifiable_homicide_circumstance = mapped_column(String(1))
    type_of_injury1 = mapped_column(String(1))
    type_of_injury2 = mapped_column(String(1))
    type_of_injury3 = mapped_column(String(1))
    type_of_injury4 = mapped_column(String(1))
    type_of_injury5 = mapped_column(String(1))
    offender_sequence_number = mapped_column(String(2))
    victim_relationship_to_offender1 = mapped_column(String(2))
    victim_relationship_to_offender2 = mapped_column(String(4))
    victim_relationship_to_offender3 = mapped_column(String(4))
    victim_relationship_to_offender4 = mapped_column(String(4))
    victim_relationship_to_offender5 = mapped_column(String(4))
    victim_relationship_to_offender6 = mapped_column(String(4))
    victim_relationship_to_offender7 = mapped_column(String(4))
    victim_relationship_to_offender8 = mapped_column(String(4))
    victim_relationship_to_offender9 = mapped_column(String(4))
    victim_relationship_to_offender10 = mapped_column(String(4))
    
class Arrestee(Base):
    __tablename__ = "arrestee_segment"
    
    db_id = mapped_column(String, primary_key = True)
    segment_level = mapped_column(String(2))
    state_code = mapped_column(String(2))
    ori = mapped_column(String(9))
    incident_number = mapped_column(String(12))
    incident_date = mapped_column(Integer)
    arrestee_sequence_number = mapped_column(String(2))
    arrest_transaction_number = mapped_column(String(12))
    arrest_date = mapped_column(Integer)
    type_of_arrest = mapped_column(String(1))
    multiple_arrestee_segment_indicator = mapped_column(String(1))
    ucr_arrest_offense_code = mapped_column(String(3))
    type_weapon_involved1 = mapped_column(String(2))
    automatic_weapon_indicator1 = mapped_column(String(1))
    type_weapon_involved2 = mapped_column(String(2))
    automatic_weapon_indicator2 = mapped_column(String(1))
    age_of_arrestee = mapped_column(String(2))
    sex_of_arrestee = mapped_column(String(1))
    race_of_arrestee = mapped_column(String(1))
    ethnicity_of_arrestee = mapped_column(String(1))
    residence_status_of_arrestee = mapped_column(String(1))
    disposition_arrestee_under_18 = mapped_column(String(1))
