from sqlalchemy import MetaData, String
from sqlalchemy.orm import DeclarativeBase, mapped_column

raw_metadata = MetaData(schema = "raw")

class Base(DeclarativeBase):
    metadata = raw_metadata

class Administrative(Base):
    __tablename__ = "administrative_segment"
    
    segment_level = mapped_column(String)
    state_code = mapped_column(String)
    ori = mapped_column(String)
    incident_number = mapped_column(String)
    incident_date = mapped_column(String)
    report_date_indicator = mapped_column(String)
    incident_date_hour = mapped_column(String)
    total_offense_segments = mapped_column(String)
    total_victim_segments = mapped_column(String)
    total_offender_segments = mapped_column(String)
    total_arrestee_segments = mapped_column(String)
    city_submission = mapped_column(String)
    cleared_exceptionally = mapped_column(String)
    exceptional_clearance_date = mapped_column(String)
    db_id = mapped_column(String, primary_key=True)

class Offense(Base):
    __tablename__ = "offense_segment"
    
    segment_level = mapped_column(String)
    state_code = mapped_column(String)
    ori = mapped_column(String)
    incident_number = mapped_column(String)
    incident_date = mapped_column(String)
    ucr_offense_code = mapped_column(String)
    offense_attempted_or_completed = mapped_column(String)
    offender_suspected_of_using1 = mapped_column(String)
    offender_suspected_of_using2 = mapped_column(String)
    offender_suspected_of_using3 = mapped_column(String)
    location_type = mapped_column(String)
    num_premises_entered = mapped_column(String)
    method_of_entry = mapped_column(String)
    type_of_criminal_activity1 = mapped_column(String)
    type_of_criminal_activity2 = mapped_column(String)
    type_of_criminal_activity3 = mapped_column(String)
    type_weapon_force_involved1 = mapped_column(String)
    automatic_weapon_indicator1 = mapped_column(String)
    type_weapon_force_involved2 = mapped_column(String)
    automatic_weapon_indicator2 = mapped_column(String)
    type_weapon_force_involved3 = mapped_column(String)
    automatic_weapon_indicator3 = mapped_column(String)
    bias_motivation = mapped_column(String)
    db_id = mapped_column(String, primary_key=True)

class Victim(Base):
    __tablename__ = "victim_segment"
    
    segment_level = mapped_column(String)
    state_code = mapped_column(String)
    ori = mapped_column(String)
    incident_number = mapped_column(String)
    incident_date = mapped_column(String)
    victim_sequence_number = mapped_column(String)
    ucr_offense_code1 = mapped_column(String)
    ucr_offense_code2 = mapped_column(String)
    ucr_offense_code3 = mapped_column(String)
    ucr_offense_code4 = mapped_column(String)
    ucr_offense_code5 = mapped_column(String)
    ucr_offense_code6 = mapped_column(String)
    ucr_offense_code7 = mapped_column(String)
    ucr_offense_code8 = mapped_column(String)
    ucr_offense_code9 = mapped_column(String)
    ucr_offense_code10 = mapped_column(String)
    type_of_victim = mapped_column(String)
    age_of_victim = mapped_column(String)
    sex_of_victim = mapped_column(String)
    race_of_victim = mapped_column(String)
    ethnicity_of_victim = mapped_column(String)
    residence_status_of_victim = mapped_column(String)
    agg_assault_homicide_circumstance1 = mapped_column(String)
    agg_assault_homicide_circumstance2 = mapped_column(String)
    additional_justifiable_homicide_circumstance = mapped_column(String)
    type_of_injury1 = mapped_column(String)
    type_of_injury2 = mapped_column(String)
    type_of_injury3 = mapped_column(String)
    type_of_injury4 = mapped_column(String)
    type_of_injury5 = mapped_column(String)
    offender_sequence_number = mapped_column(String)
    victim_relationship_to_offender1 = mapped_column(String)
    victim_relationship_to_offender2 = mapped_column(String)
    victim_relationship_to_offender3 = mapped_column(String)
    victim_relationship_to_offender4 = mapped_column(String)
    victim_relationship_to_offender5 = mapped_column(String)
    victim_relationship_to_offender6 = mapped_column(String)
    victim_relationship_to_offender7 = mapped_column(String)
    victim_relationship_to_offender8 = mapped_column(String)
    victim_relationship_to_offender9 = mapped_column(String)
    victim_relationship_to_offender10 = mapped_column(String)
    db_id = mapped_column(String, primary_key=True)

class Arrestee(Base):
    __tablename__ = "arrestee_segment"
    
    segment_level = mapped_column(String)
    state_code = mapped_column(String)
    ori = mapped_column(String)
    incident_number = mapped_column(String)
    incident_date = mapped_column(String)
    arrestee_sequence_number = mapped_column(String)
    arrest_transaction_number = mapped_column(String)
    arrest_date = mapped_column(String)
    type_of_arrest = mapped_column(String)
    multiple_arrestee_segment_indicator = mapped_column(String)
    ucr_arrest_offense_code = mapped_column(String)
    type_weapon_involved1 = mapped_column(String)
    automatic_weapon_indicator1 = mapped_column(String)
    type_weapon_involved2 = mapped_column(String)
    automatic_weapon_indicator2 = mapped_column(String)
    age_of_arrestee = mapped_column(String)
    sex_of_arrestee = mapped_column(String)
    race_of_arrestee = mapped_column(String)
    ethnicity_of_arrestee = mapped_column(String)
    residence_status_of_arrestee = mapped_column(String)
    disposition_arrestee_under_18 = mapped_column(String)
    db_id = mapped_column(String, primary_key=True)
